#pragma once
//
// 影子头文件：替换 RP-26Rune 的 foxglove flatbuffers 生成头
// （src/core/utility/foxglove/autogenerated_flatbuffers/Time_generated.h）。
// 原文件需要 flatbuffers 运行时库（本机未安装，且公开仓库里只带了 .fbs 与生成头），
// 但能量机关算法只用 foxglove::Time 的 sec()/nsec() 两个读取接口，所以这里给等价结构。

#include <cstdint>

namespace foxglove
{
struct Time
{
    Time() = default;
    Time(uint32_t sec, uint32_t nsec) : sec_(sec), nsec_(nsec) {}

    uint32_t sec() const { return sec_; }
    uint32_t nsec() const { return nsec_; }
    void mutate_sec(uint32_t sec) { sec_ = sec; }
    void mutate_nsec(uint32_t nsec) { nsec_ = nsec; }

private:
    uint32_t sec_ = 0;
    uint32_t nsec_ = 0;
};
} // namespace foxglove
